import type { Period } from '@/pages/reports/PeriodSelector'
import { periodToDates } from '@/pages/reports/PeriodSelector'

export function ReportPrintHeader({
  title,
  period,
  customFrom,
  customTo,
}: {
  title: string
  period: Period
  customFrom?: string
  customTo?: string
}) {
  const dates = periodToDates(period, customFrom, customTo)
  const fmtDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    })

  return (
    <div
      style={{
        background: '#080810',
        padding: '32px 48px 28px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        WebkitPrintColorAdjust: 'exact',
        printColorAdjust: 'exact',
      }}
    >
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ color: '#f8f8ff', fontSize: 26, fontWeight: 700, letterSpacing: 1.2 }}>Promo</span>
          <span style={{ color: '#00c2ff', fontSize: 26, fontWeight: 700, letterSpacing: 1.2 }}>[ora]</span>
          <span
            style={{
              color: '#00c2ff',
              border: '1px solid #00c2ff',
              borderRadius: 4,
              fontSize: 10,
              padding: '2px 5px',
              marginLeft: 2,
            }}
          >
            CRM
          </span>
        </div>
        <p style={{ fontSize: 11, color: '#6d6d86', marginTop: 10 }}>Generated by Promoora CRM</p>
      </div>

      <div style={{ textAlign: 'right' }}>
        <p style={{ fontSize: 22, fontWeight: 700, color: 'white', marginBottom: 6 }}>{title}</p>
        <p style={{ fontSize: 12, color: '#8a8aa1' }}>
          {fmtDate(dates.from)} - {fmtDate(dates.to)}
        </p>
      </div>
    </div>
  )
}

export function ReportPrintFooter() {
  return (
    <div
      style={{
        background: '#080810',
        padding: '16px 48px',
        marginTop: 28,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        WebkitPrintColorAdjust: 'exact',
        printColorAdjust: 'exact',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 4 }}>
        <span style={{ fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif", fontWeight: 700, color: '#f8f8ff', fontSize: 12 }}>
          Promo
        </span>
        <span style={{ fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif", fontWeight: 700, color: '#00c2ff', fontSize: 12 }}>
          [ora]
        </span>
      </div>
      <span style={{ fontSize: 11, color: '#444', fontStyle: 'italic' }}>Confidential - For internal use only</span>
      <span style={{ fontSize: 11, color: '#444', fontFamily: 'monospace' }}>{new Date().toLocaleDateString('en-IN')}</span>
    </div>
  )
}
